apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-editer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  ingressClassName: public
  rules:
    - host: www.chrom.jp
      http:
        paths:
          - path: /playground/api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /playground(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
  tls:
    - hosts:
        - www.chrom.jp
      secretName: online-editer-secret
